name: CI

on:
  release:
    types: [published]
    
jobs:
  build:
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'BoringTunSharp.sln'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Write release version
      run: |
        VERSION=${GITHUB_REF_NAME#v}
        echo Version: $VERSION
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.1

    - name: Restore dependencies
      run: nuget restore $SOLUTION

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG -p:Version=${VERSION} --no-restore
      
    - name: Publish
      if: startsWith(github.ref, 'refs/heads/release')
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}